### ISSUE TITLE
Explain the annotation

### ISSUE THREAD

**Issue by Sayyad828** [ucuapps/top-view-multi-person-tracking#1]
Hello Ivan, 

Thank you very much for sharing this dataset, I just wanted to ask about an explanation for the annotation.

An annotation file has 4 rows I assume that this means that this image has 4 people (please correct me if I'm wrong). 
Each row has 5 numbers, the first number is always "0", so can you please just explain what are these numbers, and if they represent he bounding boxes, why are they fractions?

Final thing, if my assumption is correct and these numbers represent the bounding boxes and maybe the first number indicates for the class "which is always 0 because we are trying to track only people", can you explain where is the tracking ID for the people in different frames?

Thank you very much

**Comment by IvanProdaiko94** [comment]
Hi, @Sayyad828. So, you're right saying that 0 corresponds to a `person` class, while 4 other numbers represent `the bounding box`. In order to build the tracking ID you have to perform additional actions (extracting a feature vector, associating each vector with those on next frame and so on) that are the part of DeepSort algorithm. Please, read the paper ([master thesis](https://er.ucu.edu.ua/bitstream/handle/1/1903/Prodaiko_Person%20Re-identification.pdf)) in order to understand the proposed algorithm.
